name: peterbaertcomposer
favicon: null
layout_spectrum: 0.17882
typography_spectrum: 0.47383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.375
  lightness: 0.7672238261438906
  saturation: 0.9378305154386908
  rhythmicContrast: 0.25
purpose: []
